// Generated by tools/build_catalog.py from products.csv. Do not edit by hand.
window.MARK_ONE_PRODUCTS = [
  {
    "id": "hinge-bracket-assembly",
    "name": "Hinge Bracket Assembly",
    "category": "Brackets & Hinges",
    "material": "Steel",
    "process": "Stamping & Assembly",
    "finish": "Black Coated",
    "industries": [
      "Industrial Equipment",
      "Commercial Equipment"
    ],
    "description": "A multi-piece pivoting bracket assembly with formed side plates, a slotted base channel and pinned hinge joints.",
    "specs": [
      [
        "Configuration",
        "Pivoting assembly"
      ],
      [
        "Features",
        "Formed side plates|Pinned hinge|Slotted base"
      ]
    ],
    "tags": [
      "bracket",
      "hinge",
      "assembly",
      "pivot"
    ],
    "featured": true,
    "image": "images/hinge-bracket-assembly.webp",
    "thumb": "thumbs/hinge-bracket-assembly.webp",
    "cutout": true
  },
  {
    "id": "stainless-mixing-bowl",
    "name": "Stainless Mixing Bowl",
    "category": "Food Service",
    "material": "Stainless Steel",
    "process": "Deep Drawing",
    "finish": "Polished",
    "industries": [
      "Food Service",
      "Commercial Equipment"
    ],
    "description": "A deep-drawn stainless steel mixer bowl with a rolled rim, welded side handles and mounting tabs.",
    "specs": [
      [
        "Features",
        "Rolled rim|Side handles|Mounting tabs"
      ]
    ],
    "tags": [
      "bowl",
      "mixer",
      "stainless",
      "drawn"
    ],
    "featured": true,
    "image": "images/stainless-mixing-bowl.webp",
    "thumb": "thumbs/stainless-mixing-bowl.webp",
    "cutout": true
  },
  {
    "id": "threaded-eye-bolt",
    "name": "Threaded Eye Bolt",
    "category": "Fasteners",
    "material": "Brass",
    "process": "Machining",
    "finish": "Natural",
    "industries": [
      "Industrial Equipment"
    ],
    "description": "An eye bolt with a formed ring head, a long threaded shank and a turned pilot tip.",
    "specs": [
      [
        "Features",
        "Ring eye|Threaded shank|Turned tip"
      ]
    ],
    "tags": [
      "eye bolt",
      "fastener",
      "threaded",
      "brass"
    ],
    "featured": false,
    "image": "images/threaded-eye-bolt.webp",
    "thumb": "thumbs/threaded-eye-bolt.webp",
    "cutout": true
  },
  {
    "id": "flanged-retainer-cup",
    "name": "Flanged Retainer Cup",
    "category": "Machined Components",
    "material": "Steel",
    "process": "Machining",
    "finish": "Black Oxide",
    "industries": [
      "Industrial Equipment",
      "Automotive"
    ],
    "description": "A round flanged cup with a stepped inner bore and a center cross-bar with a mounting hole.",
    "specs": [
      [
        "Features",
        "Stepped bore|Center cross-bar|Mounting hole"
      ]
    ],
    "tags": [
      "cup",
      "retainer",
      "flange",
      "round"
    ],
    "featured": false,
    "image": "images/flanged-retainer-cup.webp",
    "thumb": "thumbs/flanged-retainer-cup.webp",
    "cutout": true
  },
  {
    "id": "zinc-plated-hinge-straps",
    "name": "Zinc-Plated Hinge Straps",
    "category": "Brackets & Hinges",
    "material": "Steel",
    "process": "Stamping & Forming",
    "finish": "Yellow Zinc",
    "industries": [
      "Commercial Equipment",
      "Furniture"
    ],
    "description": "A family of formed steel straps and channels with pierced and tapped holes, finished in yellow zinc.",
    "specs": [
      [
        "Pieces shown",
        "4"
      ],
      [
        "Features",
        "Formed channel|Pierced holes|Tapped holes"
      ]
    ],
    "tags": [
      "strap",
      "hinge",
      "channel",
      "zinc"
    ],
    "featured": false,
    "image": "images/zinc-plated-hinge-straps.webp",
    "thumb": "thumbs/zinc-plated-hinge-straps.webp",
    "cutout": true
  }
];
